/**
 * Vite-plugin-side bridge setup. Called from `src/index.ts` while the workflow
 * bridge exists. Encapsulates everything bridge-specific:
 *
 *   - generates the cache wrapper at `node_modules/.cache/...` so the dev
 *     sidecar serves the `/__swe/wf/*` routes used by the runtime hook
 *   - publishes config on `globalThis` for the SvelteKit `handle` to read
 *   - returns the proxy-config service binding to add and a disposer
 *
 * Once miniflare ships cross-worker workflow routing
 * (cloudflare/workers-sdk#7459), delete `src/bridge/` and the call to
 * `setupBridge` in `src/index.ts`.
 */

import { mkdir, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';

export const BRIDGE_BINDING = '__SWE_BRIDGE';
const CACHE_DIR_REL = 'node_modules/.cache/sveltekit-add-worker-exports';
const WRAPPER_FILENAME = 'dev-worker-entry.ts';

export interface BridgeContext {
	/** Path to the generated sidecar wrapper. Use as the dev config's `main`. */
	wrapperPath: string;
	/** Service binding entry to merge into the platform-proxy wrangler config. */
	serviceBinding: { binding: string; service: string };
	/** Best-effort cleanup of generated artifacts. */
	dispose(): Promise<void>;
}

export interface SetupBridgeOptions {
	userEntryAbs: string;
	workflowBindings: readonly string[];
	sidecarName: string;
}

export async function setupBridge(options: SetupBridgeOptions): Promise<BridgeContext> {
	const cacheDir = resolve(CACHE_DIR_REL);
	await mkdir(cacheDir, { recursive: true });
	const wrapperPath = join(cacheDir, WRAPPER_FILENAME);
	const userEntryRel = relative(dirname(wrapperPath), options.userEntryAbs)
		.replace(/\\/g, '/')
		.replace(/\.(ts|tsx|js|jsx|mjs|mts)$/, '');
	await writeFile(wrapperPath, generateWrapperSource(userEntryRel, options.workflowBindings));

	// The runtime hook reads these from globalThis. We can't use vite's
	// `define` because dist/hooks.js lives in node_modules and vite doesn't
	// transform external modules in SSR by default — substitutions wouldn't
	// reach the file.
	(globalThis as Record<string, unknown>).__SWE_BRIDGE_NAME__ = BRIDGE_BINDING;
	(globalThis as Record<string, unknown>).__SWE_WORKFLOWS__ = options.workflowBindings;

	return {
		wrapperPath,
		serviceBinding: { binding: BRIDGE_BINDING, service: options.sidecarName },
		dispose: async () => {
			await unlink(wrapperPath).catch(() => {});
		}
	};
}

/**
 * Tiny glue file that wrangler bundles into the dev sidecar. The substantive
 * bridge logic lives in `./dev-handler.ts`, which the wrapper imports as a
 * package subpath. Keeping the template this small makes it unlikely to
 * harbour TypeScript errors that wouldn't be caught by tsc on the rest of
 * the package.
 */
function generateWrapperSource(userEntryRel: string, workflowBindings: readonly string[]): string {
	const importPath = JSON.stringify(userEntryRel);
	const bindingList = JSON.stringify(workflowBindings);
	return `// Auto-generated by @oselvar/sveltekit-add-worker-exports.
// Bridges Workflow bindings to SvelteKit dev. Do not edit.
import * as user from ${importPath};
export * from ${importPath};
import { createBridgeFetch } from '@oselvar/sveltekit-add-worker-exports/dev-bridge';

const userDefault = (user as { default?: { fetch?: ExportedHandlerFetchHandler } }).default;

export default {
\tfetch: createBridgeFetch({
\t\tworkflowBindings: ${bindingList},
\t\tuserFetch: userDefault?.fetch?.bind(userDefault)
\t})
} satisfies ExportedHandler;
`;
}
